---
title: "Untitled"
output: html_document
date: "2024-05-21"
---

```{r}
library(ggplot2)
library(ggpointdensity)
library(viridis)
library(tidyr)
library(plotly)
```

```{r}
ggplot(T5,aes(x,y)) + 
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") + 
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(10, 100, 1000, 10000)) + 
  coord_fixed()
```


```{r}
interestArea <- T5 %>%
  filter(x>4100 & x<4140 & y>4035 & y<4075)

interestArea2 <- T5 %>%
  filter(x>4105 & x<4135 & y>4160 & y<4190)

interestArea3 <- T5 %>%
  filter(x>4120 & x<4150 & y>4080 & y<4102)

interestArea4 <- T5 %>%
  filter(x>4120 & x<4150 & y>4100 & y<4130)
```


## 2 Sources


```{r}
#A Mixture Model for 2 Moffat Distributions
MM2MOFFAT <- function(params, x, y){
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  x2 <- params[[6]]
  y2 <- params[[7]]
  alpha2 <- params[[8]]
  beta2 <- params[[9]]
  
  lambda2 <- 1 - lambda1
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  
  Density <- lambda1*c1*v1^(-beta1) + (1 - lambda1)*c2*v2^(-beta2)
  
  return(-sum(log(Density)))
}


MM2MOFFATimage <- function(grid, params){
  x <- grid[[1]]
  y <- grid[[2]]
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  
  return(lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2))
}
```

```{r}
initialParams <- c(lambda1 = 0.5, x1 = mean(interestArea2S2$x), y1 = mean(interestArea2S2$y), alpha1 = 0.8, beta1 = 1.3,
                   x2 = mean(interestArea2S1$x), y2 = mean(interestArea2S1$y), alpha2 = 0.9, beta2 = 1.3
                   )

lowerbounds = c(0, 3900, 3900, 1e-6, 1+1e-6,
                3900, 3900, 1e-6, 1+1e-6
                )

upperbounds = c(1, 4400, 4400, Inf, Inf,
                4400, 4400, Inf, Inf
                )

MM2result <- optim(par = initialParams, fn = MM2MOFFAT, x = interestArea2$x, y = interestArea2$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MM2result
out2 <- MM2result$par
```


Visualising the results
```{r}
xRange <- seq(4105, 4135, length = 100)
yRange <- seq(4160, 4190, length = 100)
grid <- expand.grid(x = xRange, y = yRange)

Opt2params <- c(out2[[1]], out2[[2]], out2[[3]], out2[[4]], out2[[5]], 1 - out2[[1]], out2[[6]], out2[[7]], out2[[8]], out2[[9]])
zMM2 <- MM2MOFFATimage(grid, params = Opt2params)
zmat2 <- matrix(log10(zMM2), nrow = length(xRange), ncol = length(yRange))

#This is an image of the mixture model with the optimised results
par(pty = "s")
image(xRange, yRange, zmat2, xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM2)), bins = 10) +
  coord_fixed()

contours

#this is the data
interestArea2Model <- ggplot(interestArea2, aes(x = x, y = y)) +
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") +
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) +
  coord_fixed()

interestArea2Model

MMcontourData <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestArea2Model + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)

#this is the contours of the model overlayed on the data
MMcombined
```

### 5 Celestial Sources

```{r}
initialParams <- c(lambda1 = 0.7, x1 = 4115.261, y1 = 4051.904, alpha1 = 0.683, beta1 = 1.9,
                   x2 = 4124, y2 = 4063, alpha2 = 0.5, beta2 = 1.9
                   )

lowerbounds = c(1e-6, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MM2result <- optim(par = initialParams, fn = MM2MOFFAT, x = interestArea$x, y = interestArea$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MM2result
out2 <- MM2result$par
```

```{r}
xRange <- seq(4100, 4140, length = 200)
yRange <- seq(4035, 4075, length = 200)
grid <- expand.grid(x = xRange, y = yRange)

Opt2params <- c(out2[[1]], out2[[2]], out2[[3]], out2[[4]], out2[[5]], 1 - out2[[1]], out2[[6]], out2[[7]], out2[[8]], out2[[9]])
zMM2 <- MM2MOFFATimage(grid, params = Opt2params)
zmat2 <- matrix(log10(zMM2), nrow = length(xRange), ncol = length(yRange))

#This is an image of the mixture model with the optimised results
par(pty = "s")
image(xRange, yRange, zmat2, xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM2)), bins = 10) +
  coord_fixed()

contours

#this is the data
interestAreaModel <- ggplot(interestArea, aes(x = x, y = y)) +
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") +
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) +
  coord_fixed()

interestAreaModel

MMcontourData <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)

#this is the contours of the model overlayed on the data
MMcombined
```


## 3 Sources


```{r}
MM3MOFFAT <- function(params, x, y){
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  #component density 3
  x3 <- params[[11]]
  y3 <- params[[12]]
  alpha3 <- params[[13]]
  beta3 <- params[[14]]
  
  lambda3 <- 1 - lambda1 - lambda2
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  
  Density <- lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3)
  return(-sum(log(Density)))
}

MM3MOFFATimage <- function(grid, params){
  x <- grid[[1]]
  y <- grid[[2]]
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]

  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  
  return(lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3))
}
```

```{r}
#use optimised parameters from 2 source model
initialParams <- c(lambda1 = out2[[1]], x1 = out2[[2]], y1 = out2[[3]], alpha1 = out2[[4]], beta1 = out2[[5]],
                   lambda2 = 0.2 , x2 = out2[[6]], y2 = out2[[7]], alpha2 = out2[[8]], beta2 = out2[[9]],
                   x3 = 4128, y3 = 4069, alpha3 = 1, beta3 = 1.4
                   )

lowerbounds = c(1e-6, 3000, 3000, 1e-6, 1+1e-6,
                1e-6, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MM3result <- optim(par = initialParams, fn = MM3MOFFAT, x = interestArea$x, y = interestArea$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MM3result
out3 <- MM3result$par
```

```{r}
xRange <- seq(4100, 4140, length = 200)
yRange <- seq(4035, 4075, length = 200)
grid <- expand.grid(x = xRange, y = yRange)

opt3params <- c(out3[1:10],
                1 - out3[[1]] - out3[[6]], out3[11:14])

zMM3 <- MM3MOFFATimage(grid, params = opt3params)
zmat3 <- matrix(zMM3, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat3), xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM3)), bins = 10) +
  coord_fixed()

contours

interestAreaModel <- ggplot(interestArea, aes(x = x, y = y)) +
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") +
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) +
  coord_fixed()

interestAreaModel

MMcontourData <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)
MMcombined
```


## 4 Sources
```{r}
MM4MOFFAT <- function(params, x, y){
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  x4 <- params[[16]]
  y4 <- params[[17]]
  alpha4 <- params[[18]]
  beta4 <- params[[19]]
  
  lambda4 <- 1 - lambda1 - lambda2 - lambda3
  
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  
  Density <- lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4)
  
  return(-sum(log(Density)))
}

MM4MOFFATimage <- function(grid, params){
  x <- grid[[1]]
  y <- grid[[2]]
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]

  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  
  return(lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4))
}
```

```{r}
#use optimised parameters from 3 sources
initialParams4 <- c(lambda1 = out3[[1]], x1 = out3[[2]], y1 = out3[[3]], alpha1 = out3[[4]], beta1 = out3[[5]],
                   lambda2 = out3[[6]], x2 = out3[[7]], y2 = out3[[8]], alpha2 = out3[[9]], beta2 = out3[[10]],
                   lambda3 = 0.1, x3 = out3[[11]], y3 = out3[[12]], alpha3 = out3[[13]], beta3 = out3[[14]],
                   x4 = 4128, y4 = 4064, alpha4 = 0.7, beta4 = 1.2
                   )

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult4 <- optim(par = initialParams4, fn = MM4MOFFAT, x = interestArea$x, y = interestArea$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(trace = 3, maxit = 200))

MMresult4
out4 <- MMresult4$par

out4[[1]] + out4[[6]] + out4[[11]] 
```

```{r}
opt4params <- c(out4[1:15],
                1 - out4[[1]] - out4[[6]] - out4[[11]], out4[16:19]
                )

zMM4 <- MM4MOFFATimage(grid, params = opt4params)
zmat4 <- matrix(zMM4, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat4), xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM4)), bins = 10) +
  coord_fixed()

contours

MMcontourData <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)
MMcombined
```

Trying the other source
```{r}
#use optimised parameters from 3 sources
initialParams4 <- c(lambda1 = out3[[1]], x1 = out3[[2]], y1 = out3[[3]], alpha1 = out3[[4]], beta1 = out3[[5]],
                   lambda2 = out3[[6]], x2 = out3[[7]], y2 = out3[[8]], alpha2 = out3[[9]], beta2 = out3[[10]],
                   lambda3 = 0.1, x3 = out3[[11]], y3 = out3[[12]], alpha3 = out3[[13]], beta3 = out3[[14]],
                   x4 = 4130, y4 = 4073, alpha4 = 0.6, beta4 = 1.2
                   )

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult4.2 <- optim(par = initialParams4, fn = MM4MOFFAT, x = interestArea$x, y = interestArea$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(trace = 3, maxit = 200))

MMresult4.2
out4.2 <- MMresult4.2$par

out4.2[[1]] + out4.2[[6]] + out4.2[[11]] 
```

```{r}
opt4.2params <- c(out4.2[1:15],
                1 - out4.2[[1]] - out4.2[[6]] - out4.2[[11]], out4.2[16:19]
                )

zMM4.2 <- MM4MOFFATimage(grid, params = opt4.2params)
zmat4.2 <- matrix(zMM4.2, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat4.2), xlab = "x", ylab = "y", main = "2D Moffat")

contours4.2 <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM4.2)), bins = 10) +
  coord_fixed()

contours4.2

interestAreaModel <- ggplot(interestArea, aes(x = x, y = y)) +
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") +
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) +
  coord_fixed()

interestAreaModel

MMcontourData4.2 <- ggplot_build(contours4.2)$data[[1]] #extracting the contours (from the optimised function)

MMcombined <- interestAreaModel + 
  geom_path(data = MMcontourData4.2, aes(x = x, y = y, group = group), color = "red", alpha = 0.5) +
  geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5)

MMcombined
```

## 5 Sources
```{r}
MM5MOFFAT <- function(params, x, y){
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #component density 5
  x5 <- params[[21]]
  y5 <- params[[22]]
  alpha5 <- params[[23]]
  beta5 <- params[[24]]
  
  lambda5 <- 1 - lambda1 - lambda2 - lambda3 - lambda4
  
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  c5 <- (beta5 - 1)/(pi*alpha5^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  v5 <- 1+(((x-x5)^2+(y-y5)^2)/alpha5^2)
  
  Density <- lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4) + lambda5*c5*v5^(-beta5)
  
  return(-sum(log(Density)))
}

MM5MOFFATimage <- function(grid, params){
  x <- grid[[1]]
  y <- grid[[2]]
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]

  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #component density 5
  lambda5 <- params[[21]]
  x5 <- params[[22]]
  y5 <- params[[23]]
  alpha5 <- params[[24]]
  beta5 <- params[[25]]
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  c5 <- (beta5 - 1)/(pi*alpha5^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  v5 <- 1+(((x-x5)^2+(y-y5)^2)/alpha5^2)
  
  return(lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4) + lambda5*c5*v5^(-beta5))
}
```


```{r}
#use optimised parameters from 4 sources
initialParams5 <- c(lambda1 = out4[[1]], x1 = out4[[2]], y1 = out4[[3]], alpha1 = out4[[4]], beta1 = out4[[5]],
                   lambda2 = out4[[6]], x2 = out4[[7]], y2 = out4[[8]], alpha2 = out4[[9]], beta2 = out3[[10]],
                   lambda3 = out4[[11]], x3 = out4[[12]], y3 = out4[[13]], alpha3 = out4[[14]], beta3 = out4[[15]],
                   lambda4 = 0.01, x4 = out4[[16]], y4 = out4[[17]], alpha4 = out4[[18]], beta4 = out4[[19]],
                   x5 = out4.2[[16]], y5 = out4.2[[17]], alpha5 = out4.2[[18]], beta5 = out4.2[[19]]
                   )



MM5MOFFAT(initialParams5, xRange, yRange)

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult5 <- optim(par = initialParams5, fn = MM5MOFFAT, x = interestArea$x, y = interestArea$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(trace = 3, maxit = 300))

MMresult5
out5 <- MMresult5$par

out5[[1]] + out5[[6]] + out5[[11]] + out5[[16]]
```
```{r}
opt5params <- c(out5[1:20],
                1 - out5[[1]] - out5[[6]] - out5[[11]] - out5[[16]], out5[21:24]
                )

zMM5 <- MM5MOFFATimage(grid, params = opt5params)
zmat5 <- matrix(zMM5, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat5), xlab = "x", ylab = "y", main = "2D Moffat")

contours5 <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM5)), bins = 10) +
  coord_fixed()

contours5
s
interestAreaModel

MMcontourData5 <- ggplot_build(contours5)$data[[1]] #extracting the contours (from the optimised function)

MMcombined <- interestAreaModel + 
  geom_path(data = MMcontourData5, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5) #+
  # geom_path(data = MMcontourData4.2, aes(x = x, y = y, group = group), color = "red", alpha = 0.5) +
  # geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5)

MMcombined
```

### 8 Celestial Sources
```{r}
interestAreaModel3 <- ggplot(interestArea3, aes(x,y)) + 
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") + 
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) + 
  coord_fixed()

interestAreaModel3
```
```{r}
initialParams <- c(lambda1 = 0.4, x1 = 4130, y1 = 4095, alpha1 = 0.5, beta1 = 1.5,
                   x2 = 4146, y2 = 4092, alpha2 = 0.45, beta2 = 1.3
                   )

lowerbounds = c(1e-6, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MM2result <- optim(par = initialParams, fn = MM2MOFFAT, x = interestArea3$x, y = interestArea3$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MM2result
out2 <- MM2result$par
```

```{r}
xRange <- seq(4120, 4150, length = 200)
yRange <- seq(4080, 4102, length = 200)
grid <- expand.grid(x = xRange, y = yRange)

Opt2params <- c(out2[1:5],
                1 - out2[[1]], out2[6:9])

zMM2 <- MM2MOFFATimage(grid, params = Opt2params)
zmat2 <- matrix(zMM2, nrow = length(xRange), ncol = length(yRange))

#This is an image of the mixture model with the optimised results
par(pty = "s")
image(xRange, yRange, log10(zmat2), xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM2)), bins = 10) +
  coord_fixed()

contours

#this is the data
interestAreaModel3 <- ggplot(interestArea3, aes(x = x, y = y)) +
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") +
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) +
  coord_fixed()

interestAreaModel3

MMcontourData3.2 <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel3 + geom_path(data = MMcontourData3.2, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)

#this is the contours of the model overlayed on the data
MMcombined
```


```{r}
initialParams <- c(lambda1 = 0.4, x1 = 4129, y1 = 4094, alpha1 = 0.7, beta1 = 1.4,
                   lambda2 = 0.4, x2 = out2[[6]], y2 = out2[[7]], alpha2 = out2[[8]], beta2 = out2[[9]],
                   x3 = 4139, y3 = 4099, alpha3 = 0.6, beta3 = 1.4
                   )

lowerbounds = c(1e-6, 3000, 3000, 1e-6, 1+1e-6,
                1e-6, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MM3result <- optim(par = initialParams, fn = MM3MOFFAT, x = interestArea3$x, y = interestArea3$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(trace = 3))

MM3result
out3 <- MM3result$par

out3[[1]] + out3[[6]]
```

```{r}
opt3params <- c(out3[1:10],
                1 - out3[[1]] - out3[[6]], out3[11:14])

zMM3 <- MM3MOFFATimage(grid, params = opt3params)
zmat3 <- matrix(zMM3, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat3), xlab = "x", ylab = "y", main = "2D Moffat")

contours3 <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM3)), bins = 10) +
  coord_fixed()

contours3

interestAreaModel3

MMcontourData3.3 <- ggplot_build(contours3)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel3 + 
  geom_path(data = MMcontourData3.3, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5)
MMcombined
```

```{r}
initialParams5 <- c(lambda1 = 0.4, x1 = out3[[2]], y1 = out3[[3]], alpha1 = out3[[4]], beta1 = out3[[5]],
                   lambda2 = 0.35, x2 = out3[[7]], y2 = out3[[8]], alpha2 = out3[[9]], beta2 = out3[[10]],
                   lambda3 = 0.15, x3 = out3[[11]], y3 = out3[[12]], alpha3 = out3[[13]], beta3 = out3[[14]],
                   lambda4 = 0.05, x4 = 4148, y4 = 4098, alpha4 = 0.5, beta4 = 1.2,
                   x5 = 4135, y5 = 4096, alpha5 = 0.5, beta5 = 1.2
                   )

MM5MOFFAT(initialParams5, xRange, yRange)

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult5 <- optim(par = initialParams5, fn = MM5MOFFAT, x = interestArea3$x, y = interestArea3$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(maxit = 200))

MMresult5
out5 <- MMresult5$par

out5[[1]] + out5[[6]] + out5[[11]] + out5[[16]]
```


```{r}
opt5params <- c(out5[1:20], 
                1 - out5[[1]] - out5[[6]] - out5[[11]] - out5[[16]], out5[21:24])

zMM5 <- MM5MOFFATimage(grid, params = opt5params)
zmat5 <- matrix(zMM5, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat5), xlab = "x", ylab = "y", main = "2D Moffat")

contours5 <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM5)), bins = 10) +
  coord_fixed()

contours5

interestAreaModel3

MMcontourData3.5 <- ggplot_build(contours5)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel3 + 
  geom_path(data = MMcontourData3.5, aes(x = x, y = y, group = group), color = "green", alpha = 0.5) +
  geom_path(data = MMcontourData3.3, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5)
MMcombined
```


## 6 Sources

```{r}
MM6MOFFAT <- function(params, x, y){
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #component density 5
  lambda5 <- params[[21]]
  x5 <- params[[22]]
  y5 <- params[[23]]
  alpha5 <- params[[24]]
  beta5 <- params[[25]]
  
  #component density 6
  x6 <- params[[26]]
  y6 <- params[[27]]
  alpha6 <- params[[28]]
  beta6 <- params[[29]]
  
  lambda6 <- 1 - lambda1 - lambda2 - lambda3 - lambda4 - lambda5
  
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  c5 <- (beta5 - 1)/(pi*alpha5^2)
  c6 <- (beta6 - 1)/(pi*alpha6^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  v5 <- 1+(((x-x5)^2+(y-y5)^2)/alpha5^2)
  v6 <- 1+(((x-x6)^2+(y-y6)^2)/alpha6^2)
  
  Density <- lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4) + lambda5*c5*v5^(-beta5) + lambda6*c6*v6^(-beta6)
  
  return(-sum(log(Density)))
}

MM6MOFFATimage <- function(grid, params){
  x <- grid[[1]]
  y <- grid[[2]]
  
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]

  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #component density 5
  lambda5 <- params[[21]]
  x5 <- params[[22]]
  y5 <- params[[23]]
  alpha5 <- params[[24]]
  beta5 <- params[[25]]
  
  #component density 6
  lambda6 <- params[[26]]
  x6 <- params[[27]]
  y6 <- params[[28]]
  alpha6 <- params[[29]]
  beta6 <- params[[30]]
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  c5 <- (beta5 - 1)/(pi*alpha5^2)
  c6 <- (beta6 - 1)/(pi*alpha6^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  v5 <- 1+(((x-x5)^2+(y-y5)^2)/alpha5^2)
  v6 <- 1+(((x-x6)^2+(y-y6)^2)/alpha6^2)
  
  return(lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4) + lambda5*c5*v5^(-beta5) + lambda6*c6*v6^(-beta6))
}
```

```{r}
interestAreaModel3
out5
```

```{r}
interestArea3.6 <- interestArea3 %>%
  filter(x>4120 & x<4130 & y>4097 & y<4102)

IA3.6 <- ggplot(interestArea3.6, aes(x,y)) + 
  geom_point(shape = ".") + 
  coord_fixed()

IA3.6

nrow(interestArea3.6)
```
```{r}
initGuess <- c(x0 = 4125, y0 = 4095, alpha = 1, beta = 2)
lowerBounds <- c(0, 0, 1e-6, 1+1e-6)

result3.6 <- optim(par = initGuess, fn = NLL2D, gr = deriv2DNLL, x = interestArea3.6$x, y = interestArea3.6$y, method = "L-BFGS-B", lower = lowerBounds)
result3.6
optim3.6Par <- result3.6$par
optim3.6Par
```

```{r}
xRange <- seq(4120, 4130, length = 100)
yRange <- seq(4097, 4102, length = 100)
grid <- expand.grid(x = xRange, y = yRange)

amplitude <- (optim3.6Par[[4]]-1)/(pi*optim3.6Par[[3]]^2)
parameters <- c(amplitude, optim3.6Par)

z3.6<- Moffat2D(grid, parameters)
z3.6Matrix <- matrix(z3.6, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, z3.6Matrix, xlab = "x", ylab = "y", main = "2D Moffat")

contours3.6 <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = z3.6), bins = 10) +
  coord_fixed()

contours

MMcontour3.6 <- ggplot_build(contours3.6)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- IA3.6 + 
  geom_path(data = MMcontour3.6, aes(x = x, y = y, group = group), color = "green", alpha = 0.5)
MMcombined
```

```{r}
initialParams6 <- c(lambda1 = 0.45, x1 = out5[[2]], y1 = out5[[3]], alpha1 = out5[[4]], beta1 = out5[[5]],
                   lambda2 = 0.25, x2 = out5[[7]], y2 = out5[[8]], alpha2 = out5[[9]], beta2 = out5[[10]],
                   lambda3 = 0.15, x3 = out5[[12]], y3 = out5[[13]], alpha3 = out5[[14]], beta3 = out5[[15]],
                   lambda4 = 0.07, x4 = out5[[17]], y4 = out5[[18]], alpha4 = out5[[19]], beta4 = out5[[20]],
                   lambda5 = 0.07, x5 = out5[[21]], y5 = out5[[22]], alpha5 = out5[[23]], beta5 = out5[[24]],
                   x6 = optim3.6Par[[1]], y6 = optim3.6Par[[2]], alpha6 = optim3.6Par[[3]], beta6 = optim3.6Par[[4]]
                   )

MM6MOFFAT(initialParams6, xRange, yRange)

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult6 <- optim(par = initialParams6, fn = MM6MOFFAT, x = interestArea3$x, y = interestArea3$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(trace = 3, maxit = 2000))

out5

MMresult6
out6 <- MMresult6$par

out6[[1]] + out6[[6]] + out6[[11]] + out6[[16]] + out6[[21]]
```

```{r}
opt6params <- c(out6[[1]], out6[[2]], out6[[3]], out6[[4]], out6[[5]],
                out6[[6]], out6[[7]], out6[[8]], out6[[9]], out5[[10]],
                out6[[11]], out6[[12]], out6[[13]], out6[[14]], out6[[15]],
                out6[[16]], out6[[17]], out6[[18]], out6[[19]], out6[[20]], 
                out6[[21]], out6[[22]], out6[[23]], out6[[24]], out6[[25]], 
                1 - out6[[1]] - out6[[6]] - out6[[11]] - out6[[16]] - out6[[26]], out6[[26]], out6[[27]], out6[[28]], out6[[29]]
                )

zMM6 <- MM5MOFFATimage(grid, params = opt6params)
zmat6 <- matrix(zMM6, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat6), xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log(zMM6, 50)), bins = 10) +
  coord_fixed()

contours

interestAreaModel3

MMcontourData3.6 <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- interestAreaModel3 + 
  geom_path(data = MMcontourData3.6, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5) #+
  # geom_path(data = MMcontourData3.5, aes(x = x, y = y, group = group), color = "green", alpha = 0.5) +
  # geom_path(data = MMcontourData3.3, aes(x = x, y = y, group = group), color = "blue", alpha = 0.5) +
  # geom_path(data = MMcontourData3.2, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)
MMcombined
```

## 8 Sources

```{r}
MM8MOFFAT <- function(params, x, y){
  #component density 1
  lambda1 <- params[[1]]
  x1 <- params[[2]]
  y1 <- params[[3]]
  alpha1 <- params[[4]]
  beta1 <- params[[5]]
  
  #component density 2
  lambda2 <- params[[6]]
  x2 <- params[[7]]
  y2 <- params[[8]]
  alpha2 <- params[[9]]
  beta2 <- params[[10]]
  
  #component density 3
  lambda3 <- params[[11]]
  x3 <- params[[12]]
  y3 <- params[[13]]
  alpha3 <- params[[14]]
  beta3 <- params[[15]]
  
  #component density 4
  lambda4 <- params[[16]]
  x4 <- params[[17]]
  y4 <- params[[18]]
  alpha4 <- params[[19]]
  beta4 <- params[[20]]
  
  #component density 5
  lambda5 <- params[[21]]
  x5 <- params[[22]]
  y5 <- params[[23]]
  alpha5 <- params[[24]]
  beta5 <- params[[25]]
  
  #component density 6
  lambda6 <- params[[26]]
  x6 <- params[[27]]
  y6 <- params[[28]]
  alpha6 <- params[[29]]
  beta6 <- params[[30]]
  
  #component density 7
  lambda7 <- params[[31]]
  x7 <- params[[32]]
  y7 <- params[[33]]
  alpha7 <- params[[34]]
  beta7 <- params[[35]]
  
  #component density 8
  x8 <- params[[36]]
  y8 <- params[[37]]
  alpha8 <- params[[38]]
  beta8 <- params[[39]]
  
  lambda8 = 1 - lambda1 - lambda2 - lambda3 - lambda4 - lambda5 - lambda6 - lambda7
  
  #common terms
  c1 <- (beta1 - 1)/(pi*alpha1^2)
  c2 <- (beta2 - 1)/(pi*alpha2^2)
  c3 <- (beta3 - 1)/(pi*alpha3^2)
  c4 <- (beta4 - 1)/(pi*alpha4^2)
  c5 <- (beta5 - 1)/(pi*alpha5^2)
  c6 <- (beta6 - 1)/(pi*alpha6^2)
  c7 <- (beta7 - 1)/(pi*alpha7^2)
  c8 <- (beta8 - 1)/(pi*alpha8^2)
  
  v1 <- 1+(((x-x1)^2+(y-y1)^2)/alpha1^2)
  v2 <- 1+(((x-x2)^2+(y-y2)^2)/alpha2^2)
  v3 <- 1+(((x-x3)^2+(y-y3)^2)/alpha3^2)
  v4 <- 1+(((x-x4)^2+(y-y4)^2)/alpha4^2)
  v5 <- 1+(((x-x5)^2+(y-y5)^2)/alpha5^2)
  v6 <- 1+(((x-x6)^2+(y-y6)^2)/alpha6^2)
  v7 <- 1+(((x-x7)^2+(y-y7)^2)/alpha7^2)
  v8 <- 1+(((x-x8)^2+(y-y8)^2)/alpha8^2)
  
  Density <- lambda1*c1*v1^(-beta1) + lambda2*c2*v2^(-beta2) + lambda3*c3*v3^(-beta3) + lambda4*c4*v4^(-beta4) + lambda5*c5*v5^(-beta5) + lambda6*c6*v6^(-beta6) + lambda7*c7*v7^(-beta7) + lambda8*c8*v8^(-beta8)
  
  return(-sum(log(Density)))
}
```


```{r}
initialParams8 <- c(lambda1 = 0.35, x1 = 4129.4, y1 = 4094.5, alpha1 = 0.8, beta1 = 1.4,
                   lambda2 = 0.3, x2 = 4146.5, y2 = 4091.5, alpha2 = 0.6, beta2 = 1.4,
                   lambda3 = 0.1, x3 = 418.7, y3 = 4098.7, alpha3 = 0.73, beta3 = 2.2,
                   lambda4 = 0.05, x4 = 4147.9, y4 = 4098.8, alpha4 = 0.89, beta4 = 2.5,
                   lambda5 = 0.05, x5 = 4135, y5 = 4096, alpha5 = 0.8, beta5 = 2,
                   lambda6 = 0.05, x6 = 4146, y6 = 4088, alpha6 = 0.8, beta6 = 2,
                   lambda7 = 0.05, x7 = 4134, y7 = 4099, alpha7 = 0.8, beta7 = 2,
                   lambda8 = 0.05, x8 = 4126, y8 = 4099, alpha8 = 0.8, beta8 = 2
                   )

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult8 <- optim(par = initialParams8, fn = MM8MOFFAT, x = interestArea3$x, y = interestArea3$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MMresult8
out8 <- MMresult8$par
```




## Interest Area 4

```{r}
InterestArea4Model <- ggplot(interestArea4,aes(x,y)) + 
  geom_pointdensity(adjust = 0.05, size = 0.1, shape = "1") + 
  scale_color_viridis(direction = -1, option = "B", trans = "log", breaks = c(4, 16, 64)) + 
  coord_fixed()

InterestArea4Model
```

```{r}
initialParams5 <- c(lambda1 = 0.3, x1 = 4122, y1 = 4115, alpha1 = 0.5, beta1 = 1.5,
                   lambda2 = 0.25, x2 = 4132, y2 = 4110, alpha2 = 0.45, beta2 = 1.3,
                   lambda3 = 0.25, x3 = 4128, y3 = 4107, alpha3 = 0.6, beta3 = 1.4,
                   lambda4 = 0.1, x4 = 4125, y4 = 4119, alpha4 = 0.5, beta4 = 1.2,
                   x5 = 4139, y5 = 4108, alpha5 = 0.5, beta5 = 1.2
                   )

MM5MOFFAT(initialParams5, xRange, yRange)

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult5 <- optim(par = initialParams5, fn = MM5MOFFAT, x = interestArea4$x, y = interestArea4$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds)

MMresult5
out5 <- MMresult5$par

out5[[1]] + out5[[6]] + out5[[11]] + out5[[16]]
```

```{r}
xRange <- seq(4120, 4150, length = 200)
yRange <- seq(4100, 4130, length = 200)
grid <- expand.grid(x = xRange, y = yRange)

opt5params <- c(out5[1:20], 
                1 - out5[[1]] - out5[[6]] - out5[[11]] - out5[[16]], out5[21:24])

zMM5 <- MM5MOFFATimage(grid, params = opt5params)
zmat5 <- matrix(zMM5, nrow = length(xRange), ncol = length(yRange))
par(pty = "s")
image(xRange, yRange, log10(zmat5), xlab = "x", ylab = "y", main = "2D Moffat")

contours <- ggplot(grid, aes(x = x, y = y)) + 
  stat_contour(aes(z = log10(zMM5)), bins = 10) +
  coord_fixed()

contours

MMcontourData <- ggplot_build(contours)$data[[1]] #extracting the contours (from the optimised function)
MMcombined <- InterestArea4Model + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)

InterestArea4Model
MMcombined

RAW4 <- ggplot(interestArea4,aes(x,y)) +
  geom_point(size = 0.5) +
  coord_fixed()

RAW4 + geom_path(data = MMcontourData, aes(x = x, y = y, group = group), color = "red", alpha = 0.5)
```

```{r}
initialParams6 <- c(lambda1 = 0.25, x1 = out5[[2]], y1 = out5[[3]], alpha1 = out5[[4]], beta1 = out5[[5]],
                   lambda2 = 0.25, x2 = out5[[7]], y2 = out5[[8]], alpha2 = out5[[9]], beta2 = out5[[10]],
                   lambda3 = 0.2, x3 = out5[[12]], y3 = out5[[13]], alpha3 = out5[[14]], beta3 = out5[[15]],
                   lambda4 = 0.1, x4 = out5[[17]], y4 = out5[[18]], alpha4 = out5[[19]], beta4 = out5[[20]],
                   lambda5 = 0.1, x5 = out5[[21]], y5 = out5[[22]], alpha5 = out5[[23]], beta5 = out5[[24]],
                   x6 = 4136, y6 = 4114, alpha6 = 0.62, beta6 = 1.7
                   )

MM6MOFFAT(initialParams6, xRange, yRange)

lowerbounds = c(0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                0, 3000, 3000, 1e-6, 1+1e-6,
                3000, 3000, 1e-6, 1+1e-6
                )

upperbounds = c(1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                1, 5000, 5000, Inf, Inf,
                5000, 5000, Inf, Inf
                )

MMresult6 <- optim(par = initialParams6, fn = MM6MOFFAT, x = interestArea4$x, y = interestArea4$y, method = "L-BFGS-B", lower = lowerbounds, upper = upperbounds, control = list(maxit = 200, trace = 3))

out5

MMresult6
out6 <- MMresult6$par

out6[[1]] + out6[[6]] + out6[[11]] + out6[[16]] + out6[[21]]
```