---
title: "Exploring R"
output:
  word_document: default
  html_document: default
date: '2023-11-01'
---

```{r}
library(ggplot2)
library(plotly)
library(readr)
library(ggpointdensity)
library(viridis)
library(tidyr)
library(fitdistrplus)
library(rlang)
```

```{r}
set.seed(0)
g1 <- rgamma(1000, shape = 2, rate = 1)

set.seed(1)
g2 <- rgamma(1000, shape = 10, rate = 1)

set.seed(2)
g3 <- rgamma(1000, shape = 2, rate = 10)

set.seed(3)
g4 <- rgamma(1000, shape = 10, rate = 10)

par(mfrow = c(2,2))
hist(g1)
hist(g2)
hist(g3)
hist(g4)
```

```{r}
(function(x, y){ z <- x^2 + y^2; x+y+z })(0:7, 1)
norm <- function(x) sqrt(x%*%x)
norm(1:4)

```


```{r}
#Generate Random Data
set.seed(6)
dat <- rnorm(1000)
```


```{r}
#Moffat 1D
#One Dimensional Moffat Model

#Model Formula
#f(x) = A(1+(x-mu)^2/gamma^2)^-alpha

#Parameters
#A = Amplitude
#mu = the x position of the maximum of the model 
#gamma = core width of the model
#alpha = power index

#Defaults
#Amplitude = 1
#mu = 0
#gamma = 1
#alpha = 1

dMoffat1D <- function(x, amplitude, mu, gamma, alpha){amplitude*(1+((x-mu)/gamma)^2)^-alpha}

Moffat1D_Deriv <- function(x, amplitude, mu, gamma, alpha){
  chain = (1 + (x - mu)^2 / gamma^2)
  d_A = chain^(-alpha)
  d_mu = 2*amplitude*alpha*(x - mu)*d_A/(chain*gamma^2)
  d_gamma = 2*amplitude*alpha*((x - mu)^2)*d_A/(chain*gamma^3)
  d_alpha = -amplitude*d_A*log(chain)
  
  return(list(c(d_A, d_mu, d_gamma, d_alpha)))
}
```

```{r}
plot(dat)
hist(dat)
```
```{r}
dMoffat1D(2, 1, 0, 1, 1)
x <- c(-10:10)
plot(dMoffat1D(x, 1, 0, 1, 1), )
```
```{r}
Moffat1D_Deriv(0.5, 1, 0, 1, 1)
```

```{r}
set.seed(8)

randata <- rgamma(1000, 9, 2)
plot(randata)
hist(randata)
beta = 2
alpha = 9
```


```{r}
Gamma <- function(x, alpha, beta){
  ((beta^alpha)/factorial(alpha-1))* x^(alpha-1)* exp(-beta*x)
}

range <- seq(0,25, by=0.1)


plot(Gamma(range, 9, 2))
plotdist(randata, demp = TRUE)

#check
Gamma(5, 9, 2)
dgamma(5, 9, 2)

#res <- optim(c(5,9,2), Gamma)
```


```{r}
#optim example code
## "wild" function , global minimum at about -15.81515
fw <- function (x)
    10*sin(0.3*x)*sin(1.3*x^2) + 0.00001*x^4 + 0.2*x+80
plot(fw, -50, 50, n = 1000, main = "optim() minimising 'wild function'")

res <- optim(50, fw, method = "SANN",
             control = list(maxit = 20000, temp = 20, parscale = 20))
res
```

```{r}
range2 <- seq(-3, 3, by = 0.1)

par(mfrow = c(2,3))
plot(dMoffat1D(range2, 1, 0, 1, 1), main = "Default parameters")
plot(dMoffat1D(range2, 1, 0, 1, 2), main = "Changing alpha")
plot(dMoffat1D(range2, 1, 1, 1, 1), main = "Changing mu")
plot(dMoffat1D(range2, 1, 0, 0.5, 1), main = "Changing gamma")
plot(dMoffat1D(range2, 4, 0, 1, 1), main = "Changing A")
plot(dMoffat1D(range2, 4, 1, 4, 4), main = "Changing all")
```
```{r}
dMoffat1D <- function(x, amplitude, mu, gamma, alpha){
  amplitude*(1+((x-mu)/gamma)^2)^-alpha
  amplitude = min(0)
  gamma = min(0)
  alpha = min(0)}

Moffat1D_Deriv <- function(x, amplitude, mu, gamma, alpha){
  chain = (1 + (x - mu)^2 / gamma^2)
  d_A = chain^(-alpha)
  d_mu = 2*amplitude*alpha*(x - mu)*d_A/(chain*gamma^2)
  d_gamma = 2*amplitude*alpha*((x - mu)^2)*d_A/(chain*gamma^3)
  d_alpha = -amplitude*d_A*log(chain)
  
  return(list(c(d_A, d_mu, d_gamma, d_alpha)))
}
#optim(c(0, 1, 0, 1, 1), dMoffat1D, Moffat1D_Deriv)
```

```{r}
#data to fit to
plotdist(line2$x)
plot(line2)

xl2 <- line2$x
plot(xl2)

line2.5 <- line2 %>%
  filter(y>4050.5 & y< 4051)
plot(line2.5)
xl2.5 <- line2.5$x
plot(xl2.5)
```

```{r}
# Define the Gaussian density function
gaussian_density <- function(x, mean, sd) {
  return(dnorm(x, mean = mean, sd = sd))
}

# Define the negative log-likelihood function for Gaussian distribution
negative_log_likelihood <- function(parameters, x) {
  mean <- parameters[1]
  sd <- parameters[2]
  
  predicted_density <- gaussian_density(x, mean, sd)
  return(-sum(log(predicted_density)))
}

# Set initial guesses for parameters
initial_guess <- c(mean = 0, sd = 1)

# Generate some sample data
set.seed(123)
sampleData <- rnorm(1000, mean = 2, sd = 1)
plot(sampleData)

# Optimize the negative log-likelihood function
result <- optim(par = initial_guess, fn = negative_log_likelihood, x = sample_data, method = "Nelder-Mead")

# Extract the optimized parameters
optimized_parameters <- result$par
print(optimized_parameters)

#plot time
xValN <- seq(min(sampleData), max(sampleData), length = 1000)
optimisedDensN <- gaussian_density(x = xVal, mean = optimized_parameters[1], sd = optimized_parameters[2])
```

```{r}
#used for plotting and negative log likelihood
MoffatNS <- function(parameters, x){
  parameters[1] <- pmax(parameters[1], 1e-6)
  amplitude <- parameters[1]
  mu <- parameters[2]
  parameters[3] <- pmax(parameters[3], 1e-6)
  gamma <- parameters[3]
  parameters[4] <- ensure_positive(parameters[4])
  alpha <- parameters[4]
  
  amplitude*(1+((x-mu)^2/gamma^2))^(-alpha)
}

#method 1 - NLL
negLogLike <- function(parameters, x){
  amplitude <- parameters[1]
    amplitude <- pmax(amplitude, 1e-6)
  mu <- parameters[2]
  gamma <- parameters[3]
    gamma <- pmax(gamma, 1e-6)
  alpha <- parameters[4]
    alpha <- pmax(alpha, 1e-6)
    #check boundary conditions
  if(amplitude <= 0 || gamma <= 0 || alpha <= 0){
    stop("Parameters must be greater than 0")
  }
  predictedDens <- MoffatNS(parameters, x)
  return(-sum(log(predictedDens)))
}

# negLogLike <- function(parameters, x){
#   amplitude <- parameters[1]
#   mu <- parameters[2]
#   gamma <- parameters[3]
#   alpha <- parameters[4]
#     #check boundary conditions
#   predictedDens <- MoffatNS(parameters, x)
#   return(-sum(log(predictedDens)))
# }
 
#Method 2 - MLE
Moffat1D <- function(parameters, x){
  amplitude <- parameters[1]
  mu <- parameters[2]
  gamma <- parameters[3]
  alpha <- parameters[4]
  
  predicted <- amplitude*(1+((x-mu)^2/gamma^2))^(-alpha)
  return(sum(predicted))
}

MoffatDeriv <- function(parameters, x){
  parameters[1] <- pmax(parameters[1], 1e-6)
  amplitude <- parameters[1]
  mu <- parameters[2]
  parameters[3] <- pmax(parameters[3], 1e-6)
  gamma <- parameters[3]
  parameters[4] <- pmax(parameters[4], 1e-6)
  alpha <- parameters[4]
  

  d_A = sum((1 + (x - mu)^2 / gamma^2)^(-alpha))
  d_mu = 2*sum(amplitude*alpha*(x - mu)*(1 + (x - mu)^2 / gamma^2)^(-alpha)/((1 + (x - mu)^2 / gamma^2)*gamma^2))
  d_gamma = 2*sum(amplitude*alpha*((x - mu)^2)*(1 + (x - mu)^2 / gamma^2)^(-alpha)/((1 + (x - mu)^2 / gamma^2)*gamma^3))
  d_alpha = -sum(amplitude*(1 + (x - mu)^2 / gamma^2)^(-alpha)*log((1 + (x - mu)^2 / gamma^2)))
  
  return(c(d_A, d_mu, d_gamma, d_alpha))
}
#set initial guesses
initialGuess <- c(amplitude = 0.4, mu = 2, gamma = 0.5, alpha = 0.4)
#set bounds
lowerBounds <- c(1e-6, -Inf, 1e-6, 1e-6)
upperBounds <- c(Inf, Inf, Inf, Inf)

#Optimise
#Method 1
result <- optim(par = initialGuess, fn = negLogLike, x = sampleData, method = "Nelder-Mead")
optimPar <- result$par
print(optimPar)
res <- optim(par = initialGuess, fn = negLogLike, x = sampleData, method = "L-BFGS-B", lower = lowerBounds)
print(res$par)
#Method 2
result2 <- optim(par = initialGuess, fn = Moffat1D, gr = MoffatDeriv, x = sampleData, method = "L-BFGS-B", lower = lowerBounds)
optimPar2 <- result2$par
print(optimPar2)

```
```{r}
#code checking
ensure_positive <- function(x) {
  if(x<= 0){
    return(1e-6)
  } else {
    return(x)
  }
}

MoffatNS <- function(parameters, x){
  parameters[1] <- pmax(parameters[1], 1e-6)
  amplitude <- parameters[1]
  mu <- parameters[2]
  parameters[3] <- pmax(parameters[3], 1e-6)
  gamma <- parameters[3]
  parameters[4] <- ensure_positive(parameters[4])
  alpha <- parameters[4]

  amplitude*(1+((x-mu)^2/gamma^2))^(-alpha)
}

negLogLike <- function(parameters, x){
  amplitude <- parameters[1]
  mu <- parameters[2]
  gamma <- parameters[3]
  alpha <- parameters[4]
    #check boundary conditions
  predictedDens <- MoffatNS(parameters, x)
  return(-sum(log(predictedDens)))
}

initialGuess <- c(0.4,1,5,2)
sample <- c(0.7, 1, 1.4)
MoffatNS(initialGuess, sample)
negLogLike(initialGuess, sample)

MoffatDeriv <- function(parameters, x){
  parameters[1] <- pmax(parameters[1], 1e-6)
  amplitude <- parameters[1]
  mu <- parameters[2]
  parameters[3] <- pmax(parameters[3], 1e-6)
  gamma <- parameters[3]
  parameters[4] <- pmax(parameters[4], 1e-6)
  alpha <- parameters[4]
  

  d_A = sum((1 + (x - mu)^2 / gamma^2)^(-alpha))
  d_mu = 2*sum(amplitude*alpha*(x - mu)*(1 + (x - mu)^2 / gamma^2)^(-alpha)/((1 + (x - mu)^2 / gamma^2)*gamma^2))
  d_gamma = 2*sum(amplitude*alpha*((x - mu)^2)*(1 + (x - mu)^2 / gamma^2)^(-alpha)/((1 + (x - mu)^2 / gamma^2)*gamma^3))
  d_alpha = -sum(amplitude*(1 + (x - mu)^2 / gamma^2)^(-alpha)*log((1 + (x - mu)^2 / gamma^2)))
  
  return(c(d_A, d_mu, d_gamma, d_alpha))
}

initialGuess <- c(0.4,2,3,1)
MoffatDeriv(initialGuess, sample)
Moffat1D(initialGuess, sample)
```


```{r}
#plot time
xVal <- seq(min(sampleData), max(sampleData), length = 1000)
optimisedDens <- MoffatNS(optimPar, xVal)
optDens2 <- MoffatNS(optimPar2, xVal)

plot(sampleData)
plot(xValN, optimisedDensN, type = "l", main = "Optimised Density Function (Gaussian)", xlab = "x", ylab = "Density")

plot(xVal, optimisedDens, type = "l", main = "Optimised Density Function (Moffat, NLL)", xlab = "x", ylab = "Density")

plot(xVal, optDens2, type = "l", main = "Optimised Density Function (Moffat, grad)", xlab = "x", ylab = "Density")

```


```{r}
#Fitting to data
xVall2 <- seq(min(xl2), max(xl2), length = 963)
plot(xl2)

#set initial guesses
initialGuess <- c(amplitude = 0.4, mu = 4115, gamma = 0.5, alpha = 0.4)

#Method 1
#l2m1 = line 2 (slice of celestial source), method 1 (negative log likelihood)
resultl2m1 <- optim(par = initialGuess, fn = negLogLike, x = xl2, method = "Nelder-Mead")
optimParl2m1 <- resultl2m1$par
print(optimParl2m1)
optDenl2m1 <- MoffatNS(optimParl2m1, xVall2)

#Method 2
#l2m2 = line 2 (slice of celestial source), method 2 (mle)
resultl2m2 <- optim(par = initialGuess, fn = Moffat1D, gr = MoffatDeriv, x = xl2, lower = lowerBounds, method = "L-BFGS-B")
optimParl2m2 <- resultl2m2$par
print(optimParl2m2)
optDenl2m2<- MoffatNS(optimParl2m2, xVall2)

#plot
par(mfrow = c(1,2))
plot(xVall2, optDenl2m1, type = "l", main = "Optimised Density Function (NLL)", xlab = "x", ylab = "Density")
plot(xVall2, optDenl2m2, type = "l", main = "Optimised Density Function", xlab = "x", ylab = "Density")

par(mfrow = c(1,3))
plot(xl2)
plot(MoffatNS(optimParl2m1, xl2))
plot(MoffatNS(optimParl2m2, xl2))
```

```{r}
#Fitting to data
xVall2.5 <- seq(min(xl2.5), max(xl2.5), length = 963)
plot(xl2.5)

#set initial guesses
initialGuess <- c(amplitude = 0.4, mu = 4115, gamma = 0.4, alpha = 0.4)

#Method 1
#l2.5m1 = line 2.5 (slice of celestial source), method 1 (negative log likelihood)
resultl2.5m1 <- optim(par = initialGuess, fn = negLogLike, x = xl2.5, method = "L-BFGS-B", lower = lowerBounds)
optimParl2.5m1 <- resultl2.5m1$par
print(optimParl2.5m1)
optDenl2.5m1 <- MoffatNS(optimParl2.5m1, xVall2.5)


#Method 2
#l2.5m2 = line 2.5 (slice of celestial source), method 2 (mle)
resultl2.5m2 <- optim(par = initialGuess, fn = Moffat1D, gr = MoffatDeriv, x = xl2.5, lower = lowerBounds, method = "L-BFGS-B")
optimParl2.5m2 <- resultl2.5m2$par
print(optimParl2.5m2)
optDenl2.5m2<- MoffatNS(optimParl2.5m2, xVall2.5)

#plot
par(mfrow = c(1,2))
plot(xVall2.5, optDenl2.5m1, type = "l", main = "Optimised Density Function (NLL)", xlab = "x", ylab = "Density")
plot(xVall2.5, optDenl2.5m2, type = "l", main = "Optimised Density Function", xlab = "x", ylab = "Density")

par(mfrow = c(1,3))
plot(xl2.5)
plot(MoffatNS(optimParl2.5m1, xl2.5))
plot(MoffatNS(optimParl2.5m2, xl2.5))
```