---
title: "POI1"
output: html_document
date: '2023-10-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(plotly)
library(readr)
library(ggpointdensity)
library(viridis)
library(tidyr)
library(fitdistrplus)
library(rlang)
```

```{r}
Terzan5 <- read.csv("C:\\Users\\Blake\\Desktop\\Uni\\Honours\\Project\\Terzan 5 X-ray events.csv")
T5 <- data.frame(Terzan5$x, Terzan5$y)
colnames(T5) <- c('x','y')
POI1 <- T5 %>%
  filter(x>4160 & x<4180 & y>4180 & y<4200)
POI2 <- T5 %>%
  filter(x>4105 & x< 4125 & y>4040 & y<4060)
```

```{r}
head(POI1)
head(POI2)
```

```{r}
ggplot(POI1, aes(x,y))+ geom_point(shape = ".") + geom_density2d() + coord_fixed()
ggplot(POI2, aes(x,y))+ geom_point(shape = ".") + geom_density2d() + coord_fixed()
```

```{r}
#setting up lines

line0 <- POI2 %>%
  filter(y>4048.5 & y< 4049.5)
line1 <- POI2 %>%
  filter(y>4049.5 & y< 4050.5)
line2 <- POI2 %>%
  filter(y>4050.5 & y< 4051.5)
line3 <- POI2 %>%
  filter(y>4051.5 & y< 4052.5)
line4 <- POI2 %>%
  filter(y>4052.5 & y< 4053.5)
line5 <- POI2 %>%
  filter(y>4053.5 & y< 4054.5)
line6 <- POI2 %>%
  filter(y>4054.5 & y< 4055.5)
lineback <- POI2 %>%
  filter(y>4055 & y< 4060)

#histograms with superimposed densities
plotdist(line0$x, histo = TRUE, demp = TRUE)
plotdist(line1$x, histo = TRUE, demp = TRUE)
plotdist(line2$x, histo = TRUE, demp = TRUE)
plotdist(line3$x, histo = TRUE, demp = TRUE)
plotdist(line4$x, histo = TRUE, demp = TRUE)
plotdist(line5$x, histo = TRUE, demp = TRUE)
plotdist(line6$x, histo = TRUE, demp = TRUE)
plotdist(lineback$x, histo = TRUE, demp = TRUE)
```

```{r}
#Q-Q and P-P plots
l0 <- fitdist(line0$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l0)
denscomp(l0)
qqcomp(l0)
ppcomp(l0)

l1 <- fitdist(line1$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l1)
denscomp(l1)
qqcomp(l1)
ppcomp(l1)

l2 <- fitdist(line2$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l2)
denscomp(l2)
qqcomp(l2)
ppcomp(l2)

l3 <- fitdist(line3$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l3)
denscomp(l3)
qqcomp(l3)
ppcomp(l3)

l4 <- fitdist(line4$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l4)
denscomp(l4)
qqcomp(l4)
ppcomp(l4)

l5 <- fitdist(line5$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l5)
denscomp(l5)
qqcomp(l5)
ppcomp(l5)

l6 <- fitdist(line6$x, "norm")
par(mfrow = c(2,2))
cdfcomp(l6)
denscomp(l6)
qqcomp(l6)
ppcomp(l6)

lb <- fitdist(lineback$x, "unif")
par(mfrow = c(2,2))
cdfcomp(lb)
denscomp(lb)
qqcomp(lb)
ppcomp(lb)
```

```{r}
band <- POI2 %>%
  filter(y>4048.5 & y< 4055.5)
ggplot() + geom_point(mapping = aes(x,y), data = line0, shape =".") + geom_point(mapping = aes(x,y), data = line1, colour = "red", shape =".") + geom_point(mapping = aes(x,y), data = line2, colour = "blue", shape =".") + geom_point(mapping = aes(x,y), data = line3, shape =".") + geom_point(mapping = aes(x,y), data = line4, colour = "blue", shape =".") + geom_point(mapping = aes(x,y), data = line5, colour = "red", shape =".") + geom_point(mapping = aes(x,y), data = line6, shape =".") + coord_fixed()
```

```{r}
line3.1 <- line3 %>%
  filter(y>4051.5 & y< 4051.7)
line3.2 <- line3 %>%
  filter(y>4051.7 & y< 4051.9)
line3.3 <- line3 %>%
  filter(y>4051.9 & y< 4052.1)
line3.4 <- line3 %>%
  filter(y>4052.1 & y< 4052.3)
line3.5 <- line3 %>%
  filter(y>4052.3 & y< 4052.5)
```

```{r}
plotdist(line3.3$x, histo = TRUE, demp = TRUE)
```
```{r}
mean(line1$x)
mean(line2$x)
mean(line3$x)
mean(line4$x)
mean(line5$x)
mean(POI2$x)
```

```{r}
line3.1$x
mean(line3.1$x)
trial <- order(line3.1$x)
plot(dMoffat1D(line3.1$x, 1, mean(line3.1$x), 1, 1))
```

